### PR TITLE
gl-framework: add GLArgument and GLComputeProgram

### PR DESCRIPTION
**Pull request by liuyinhangx**
* gl-framework: add GLArgument
* gl-framework: add GLComputeProgram
* gl-framework: support quotation marks conversion for shader
* tools: generalize double quotation marks conversion tool

### CODE REVIEW

**Comment by windyuan** [comment]
@liuyinhangx,
Others looks good except UniformOps. suggestions.
1. use namespace of XCam::UniformOps instead of class XCam::UniformOps
2. use template instead of functions UniformOps::uniform.
For instance.
               
        namespace UniformOps {
        
        template <typename TType>
        inline GLenum uniform (const GLint &location, const TType &value);
        
        template <typename TType, uint32_t dim>
        inline GLenum uniform_vect (
        	const GLint &location, const TType *value, const GLsizei &count);
        
        
        template<>
        GLenum uniform<GLfloat> (const GLint &location, const GLfloat &value)
        {
        	...
        }
        
        }

**Comment by liuyinhangx** [comment]
update patch, please help to review, thanks.

**Comment by windyuan** [comment]
Path looks good.  I'll merge that after CI passed.
A concern is that in my old memory, template may not well served if implementations move to cpp file instead of header file. Maybe the modern compiler already support that.
If CI build passed, why not merge.

**Comment by liuyinhangx** [comment]
gl-framework: add GLCommand： update some issues about code style

**Comment by windyuan** [comment]
merged.
thanks.

**Pull request merged**
